[project]
name = "procurement_requests"
version = "0.1.0"
description = "Internal Procurement project-specific Frappe extension"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["*.json", "*.txt", "*.js"]
